# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-02 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='prize',
            new_name='price',
        ),
    ]
